language: rust
dist: trusty
osx_version: xcode7.3

os:
  - linux
  - osx

git:
  depth: 1

before_script:
  - sudo easy_install virtualenv
  - virtualenv ~/virtualenv
  - source ~/virtualenv/bin/activate

script: make
if: tag IS blank

after_success:
  - npm install -g zeus-ci
  - test "$DEPLOY" && zeus-ci upload -t "application/zip+wheel" py/dist/*

matrix:
  include:
    - script: make wheel
      env: DEPLOY=mac-wheel
      osx_image: xcode6.4
      os: osx

    - script: make wheel-manylinux IMAGE=quay.io/pypa/manylinux1_x86_64
      env: DEPLOY=linux-x86-wheel
      sudo: required
      services:
        - docker

    - script: make wheel-manylinux IMAGE=quay.io/pypa/manylinux1_i686
      env: DEPLOY=linux-x86_64-wheel
      sudo: required
      services:
        - docker

    - script: make sdist
      env: DEPLOY=sdist

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/3be2453a-c595-11e7-8cdd-0a580a28020a/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
