[package]
name = "symbolic"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[workspace]

[dependencies]
symbolic-common = { path = "common" }
symbolic-demangle = { path = "demangle" }
symbolic-minidump = { path = "minidump" }
symbolic-proguard = { path = "proguard" }
symbolic-sourcemap = { path = "sourcemap" }
symbolic-symcache = { path = "symcache" }
symbolic-debuginfo = { path = "debuginfo" }

[profile.dev]
opt-level = 2
