[package]
name = "symbolic"
version = "1.1.4"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[workspace]

[dependencies]
symbolic-common = { version = "1.1.4", path = "common" }
symbolic-demangle = { version = "1.1.4", path = "demangle" }
symbolic-minidump = { version = "1.1.4", path = "minidump" }
symbolic-proguard = { version = "1.1.4", path = "proguard" }
symbolic-sourcemap = { version = "1.1.4", path = "sourcemap" }
symbolic-symcache = { version = "1.1.4", path = "symcache" }
symbolic-debuginfo = { version = "1.1.4", path = "debuginfo" }
