[package]
name = "symbolic"
version = "1.1.4"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
readme = "README.md"
description = """
A library to symbolicate and process stack traces from native applications,
minidumps, minified JavaScripts or ProGuard optimized Android apps.
"""
exclude = [
    ".vscode/**/*",
    "py/**/*",
    "scripts/**/*",
]

[workspace]

[dependencies]
symbolic-common = { version = "1.1.4", path = "common" }
symbolic-demangle = { version = "1.1.4", path = "demangle" }
symbolic-minidump = { version = "1.1.4", path = "minidump" }
symbolic-proguard = { version = "1.1.4", path = "proguard" }
symbolic-sourcemap = { version = "1.1.4", path = "sourcemap" }
symbolic-symcache = { version = "1.1.4", path = "symcache" }
symbolic-debuginfo = { version = "1.1.4", path = "debuginfo" }
