[package]
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
name = "symbolic-debuginfo"
version = "0.1.0"

[dependencies]
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
goblin = "0.0.11"
if_chain = "0.1.2"
memmap = "^0.5.0"
scroll = "0.7.0"
uuid = "0.5.0"

[dependencies.symbolic-common]
path = "../common"
features = ["with_objects", "with_dwarf"]
