[package]
name = "symbolic-debuginfo"
version = "1.1.4"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-debuginfo"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
description = """
A library to inspect and load DWARF debugging information from binaries, such
as Mach-O or ELF.
"""

[dependencies]
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
goblin = "0.0"
if_chain = "0.1"
memmap = "0.5"
scroll = "0.7"
uuid = "0.5"
symbolic-common = { path = "../common", version = "1.1.4", features = ["with_objects", "with_dwarf"] }
