[package]
name = "symbolic-minidump"
version = "1.1.3"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
build = "build.rs"

[dependencies]
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
goblin = "0.0"
symbolic-common = { version = "1.1.3", path = "../common" }
symbolic-debuginfo = { version = "1.1.3", path = "../debuginfo" }
uuid = { version = "0.5", features = ["use_std"] }
