[package]
name = "symbolic-minidump"
version = "1.0.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
breakpad = "0.1"
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
goblin = "0.0"

[dependencies.symbolic-common]
path = "../common"

[dependencies.symbolic-debuginfo]
path = "../debuginfo"
