[package]
name = "symbolic-minidump"
version = "1.1.4"
license = "MIT"
authors = [
    "Armin Ronacher <armin.ronacher@active-4.com>",
    "Jan Michael Auer <mail@jauer.org>",
]
documentation = "https://docs.rs/symbolic-minidump"
homepage = "https://github.com/getsentry/symbolic"
repository = "https://github.com/getsentry/symbolic"
readme = "README.md"
description = """
A library to process and inspect Minidump crash reports
"""
build = "build.rs"

[dependencies]
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
goblin = "0.0"
symbolic-common = { version = "1.1.4", path = "../common" }
symbolic-debuginfo = { version = "1.1.4", path = "../debuginfo" }
uuid = { version = "0.5", features = ["use_std"] }
