[package]
name = "symbolic-proguard"
version = "1.1.1"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
symbolic-common = { path = "../common" }
proguard = "0.4.0"
uuid = "0"
