[package]
name = "symbolic-proguard"
version = "1.1.3"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
symbolic-common = { version = "1.1.3", path = "../common" }
proguard = "1.0.0"
uuid = "0"
