[package]
name = "symbolic-symcache"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
symbolic-common = { path = "../common", features = ["with_dwarf", "with_objects"] }
symbolic-debuginfo = { path = "../debuginfo" }
uuid = { version = "^0.4", features = ["serde"] }
gimli = "0.14.0"
