[package]
name = "symbolic-symcache"
version = "1.1.4"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
symbolic-common = { version = "1.1.4", path = "../common", features = ["with_dwarf", "with_objects"] }
symbolic-debuginfo = { version = "1.1.4", path = "../debuginfo" }
symbolic-demangle = { version = "1.1.4", path = "../demangle" }
uuid = { version = "^0.5", features = ["serde"] }
gimli = { git = "https://github.com/gimli-rs/gimli.git" }
fallible-iterator = "0.1"
lru-cache = "0.1"
owning_ref = "0.3"
fnv = "1.0"
num = "0.1"
matches = "0.1"
if_chain = "0.1"
dmsort = "0.1"

[dev-dependencies]
clap = "2"
