[package]
name = "symbolic-cabi"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "symbolic"
crate-type = ["cdylib"]

[workspace]

[dependencies]
uuid = "0"

[dependencies.symbolic-common]
path = "../common"
features = ["with_dwarf", "with_objects"]

[dependencies.symbolic-demangle]
path = "../demangle"

[dependencies.symbolic-debuginfo]
path = "../debuginfo"

[dependencies.symbolic-symcache]
path = "../symcache"

[replace]
"goblin:0.0.11" = { git = "https://github.com/m4b/goblin", rev = "2675fd5d3bbafec360a6ddaa208a6f1643e429cd" }
