[package]
name = "symbolic-cabi"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "symbolic"
crate-type = ["cdylib"]

[workspace]

[dependencies.symbolic-common]
path = "../common"
features = ["with_dwarf", "with_objects"]

[dependencies.symbolic-demangle]
path = "../demangle"

[dependencies.symbolic-debuginfo]
path = "../debuginfo"

[dependencies.symbolic-symcache]
path = "../symcache"
