[package]
name = "symbolic-cabi"
version = "1.1.3"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "symbolic"
crate-type = ["cdylib"]

[workspace]

[profile.release]
debug = true
lto = true

[dependencies]
uuid = "0"
backtrace = "0"
symbolic-common = { version = "1.1.3", path = "../common", features = ["with_dwarf", "with_objects", "with_sourcemaps"] }
symbolic-demangle = { version = "1.1.3", path = "../demangle" }
symbolic-debuginfo = { version = "1.1.3", path = "../debuginfo" }
symbolic-symcache = { version = "1.1.3", path = "../symcache" }
symbolic-sourcemap = { version = "1.1.3", path = "../sourcemap" }
symbolic-proguard = { version = "1.1.3", path = "../proguard" }
symbolic-minidump = { version = "1.1.3", path = "../minidump" }

[replace]
"goblin:0.0.11" = { git = "https://github.com/m4b/goblin", rev = "d40a1a217cd0fd23d01d3928612743100ad33561" }
