[package]
name = "symbolic-cabi"
version = "0.9.2"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[lib]
name = "symbolic"
crate-type = ["cdylib"]

[workspace]

[profile.release]
debug = true
lto = true

[dependencies]
uuid = "0"
backtrace = "0"
symbolic-common = { path = "../common", features = ["with_dwarf", "with_objects"] }
symbolic-demangle = { path = "../demangle" }
symbolic-debuginfo = { path = "../debuginfo" }
symbolic-symcache = { path = "../symcache" }

[replace]
"goblin:0.0.11" = { git = "https://github.com/mitsuhiko/goblin", rev = "c4fd7a6a8abbf422166748d1a5321be720542c51" }
