[package]
name = "symbolic-common"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
error-chain = "0.11"
memmap = "^0.5.0"
gimli = { git = "https://github.com/gimli-rs/gimli.git", optional = true }
goblin = { version = "0.0.11", optional = true }
scroll = { version = "0.7.0", optional = true }
mach_object = { version = "0.1", optional = true }
owning_ref = "0.3"

[features]
default = []
with_dwarf = ["gimli"]
with_objects = ["goblin", "scroll", "mach_object"]
